"""empty message

Revision ID: 10e629d6d918
Revises: f42facb4de68
Create Date: 2024-09-06 08:38:00.515770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e629d6d918'
down_revision = 'f42facb4de68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno', sa.String(length=100), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('cafeteria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cafeteria_id'], ['cafeteria.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('rut'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('usuario_beneficio',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('beneficio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beneficio_id'], ['beneficio.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'beneficio_id')
    )
    op.drop_table('user_beneficio')
    op.drop_table('user')
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('usuario_id')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('apellido_paterno', sa.VARCHAR(length=100), nullable=False),
    sa.Column('apellido_materno', sa.VARCHAR(length=100), nullable=False),
    sa.Column('rut', sa.VARCHAR(length=12), nullable=False),
    sa.Column('fecha_nacimiento', sa.DATE(), nullable=False),
    sa.Column('usuario', sa.VARCHAR(length=50), nullable=False),
    sa.Column('correo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('contraseña', sa.VARCHAR(length=255), nullable=False),
    sa.Column('rol_id', sa.INTEGER(), nullable=False),
    sa.Column('cafeteria_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cafeteria_id'], ['cafeteria.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('rut'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('user_beneficio',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('beneficio_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['beneficio_id'], ['beneficio.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'beneficio_id')
    )
    op.drop_table('usuario_beneficio')
    op.drop_table('usuario')
    # ### end Alembic commands ###
