"""empty message

Revision ID: d8a802dabf92
Revises: 
Create Date: 2024-09-11 17:07:38.764913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a802dabf92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoria_producto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('rut'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('pais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('salario_base', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comuna',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cafeteria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('comuna_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comuna_id'], ['comuna.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combo_menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('cafeteria_id', sa.Integer(), nullable=False),
    sa.Column('tipo_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cafeteria_id'], ['cafeteria.id'], ),
    sa.ForeignKeyConstraint(['tipo_item_id'], ['tipo_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mesa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('qr_code', sa.String(length=255), nullable=False),
    sa.Column('cafeteria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cafeteria_id'], ['cafeteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.Float(), nullable=True),
    sa.Column('categoria_producto_id', sa.Integer(), nullable=False),
    sa.Column('cafeteria_id', sa.Integer(), nullable=False),
    sa.Column('tipo_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cafeteria_id'], ['cafeteria.id'], ),
    sa.ForeignKeyConstraint(['categoria_producto_id'], ['categoria_producto.id'], ),
    sa.ForeignKeyConstraint(['tipo_item_id'], ['tipo_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno', sa.String(length=100), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('cafeteria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cafeteria_id'], ['cafeteria.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('rut'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('calificacion_producto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_rut', sa.String(length=12), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_rut'], ['cliente.rut'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_combo_menu',
    sa.Column('combo_menu_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['combo_menu_id'], ['combo_menu.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('combo_menu_id', 'producto_id')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_rut', sa.String(length=12), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_rut'], ['cliente.rut'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('monto_total', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('cliente_rut', sa.String(length=12), nullable=False),
    sa.Column('cafeteria_id', sa.Integer(), nullable=False),
    sa.Column('mesero_rut', sa.String(length=12), nullable=True),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cafeteria_id'], ['cafeteria.id'], ),
    sa.ForeignKeyConstraint(['cliente_rut'], ['cliente.rut'], ),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesa.id'], ),
    sa.ForeignKeyConstraint(['mesero_rut'], ['usuario.rut'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_venta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.Column('tipo_item_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_item_id'], ['tipo_item.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_rut', sa.String(length=12), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_rut'], ['cliente.rut'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_pedidos')
    op.drop_table('detalle_venta')
    op.drop_table('venta')
    op.drop_table('favoritos')
    op.drop_table('detalle_combo_menu')
    op.drop_table('calificacion_producto')
    op.drop_table('usuario')
    op.drop_table('producto')
    op.drop_table('mesa')
    op.drop_table('combo_menu')
    op.drop_table('cafeteria')
    op.drop_table('comuna')
    op.drop_table('region')
    op.drop_table('tipo_item')
    op.drop_table('rol')
    op.drop_table('pais')
    op.drop_table('cliente')
    op.drop_table('categoria_producto')
    op.drop_table('beneficio')
    # ### end Alembic commands ###
